import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from '../lib/auth'
import styles from '../styles/Home.module.css'

export default function Home() {
  const auth = useAuth()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          {auth.user ? (
            <p>
              <code className={styles.code}>{auth?.user?.email}</code>
              <Image src="/logout.svg" onClick={(e) => auth.signout()} className={styles.logout} alt="Sign Out" width={20} height={20} />
            </p>
          ) : (
            <p onClick={(e) => auth.signInWithGoogle()}>
              <code className={styles.code}>Sign In with Google</code>
            </p>
          )}

          <div>
            By Team Stealth Mode at CRIF Hackathon
          </div>
        </div>

        <div className={styles.center}>
          {auth.user ? (
            <div>
              <p className={styles.code}>Your Social Credit Score is!</p>
              <h1 className={styles.big}>1000</h1>
            </div>
          ) : (
            <p className={styles.code}>Sign in to see your Social Credit Score</p>
          )}
        </div>
      </main>
    </>
  )
}
